# Generated by Django 6.1.1 on 2026-09-20 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organization name')),
                ('slug', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(regex='^[-a-zA-Z0-9_]+$')], verbose_name='Organization slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
            ],
            options={
                'verbose_name': 'organization',
                'ordering': ['name'],
            },
        ),
    ]
