# Generated by Django 6.1.1 on 2026-09-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('approver', 'Approver'), ('admin', 'Admin')], default='member', max_length=16, verbose_name='Role'),
        ),
    ]
